UnrealBuildTool: Initial support for Clang 13 Hack to workaround clang-cl bug in LC_StringUtil.cpp is finally no longer necessary with Clang 13
Outstanding Issues:
Unresloved externals in ClangEditor (FRHI*)
error: ordered comparison of function pointers ('Electra::fastdelegate::DelegateMemento::GenericFuncPtr' (aka
    'void (*)()') and 'Electra::fastdelegate::DelegateMemento::GenericFuncPtr') [-Werror,-Wordered-compare-function-
    pointers]

#rnx
#rb none
#preflight 61d33dff932a02483cb454bc

[CL 18503088 by Joe Kirchoff in 5.0 branch]